### ISSUE TITLE
Pandas dependency 버전이 너무 낮습니다

### ISSUE THREAD

**Issue by forcecore** [DonghyungKo/kiwoom_api_handler#12]
안녕하세요
코어 부분에 실질적인 pandas dependency는 없는데 requirements.txt 에 서술된 버전 정보는 버전이 너무 낮은 것 같습니다. 검토 후 dependency를 낮추거나 없애는 방향으로 가는 것이 좋을 것 같습니다.

**Comment by DonghyungKo** [comment]
Closed By #13 

이슈 남겨주셔서 감사드립니다.
