### ISSUE TITLE
kiwoom_api.confg 가 없어 실행이 안 됩니다

### ISSUE THREAD

**Issue by forcecore** [DonghyungKo/kiwoom_api_handler#6]
TRName이나 ReturnCode등을 제공하는 중요 파일들로 보이는데 git clone으로 받으면 실행이 되지 않는 것으로 보입니다. (pip install로는 안 해봐서, 그 때엔 되는지는 모르겠습니다)

**Comment by DonghyungKo** [comment]
https://github.com/DonghyungKo/kiwoom_api_handler/pull/7 에서 버그 수정 하였습니다!
