### ISSUE TITLE
calcShiftedPrice, k가 정의되지 않은 버그

### ISSUE THREAD

**Issue by forcecore** [DonghyungKo/kiwoom_api_handler#8]
https://github.com/DonghyungKo/kiwoom_api_handler/blob/96a4246349336283c1b11ee638ed4794c5c826e8/kiwoom_api/utility/_tick_calculator.py#L59

안녕하세요, IDE에서 이런 저런 것 고치다가 발견했습니다.
k가 아마도 tickShift 로 개명되었던 것 같습니다.

**Comment by DonghyungKo** [comment]
앗 감사합니다!
알려주신 부분 반영해서 수정하도록 하겠습니다!

**Comment by DonghyungKo** [comment]
https://github.com/DonghyungKo/kiwoom_api_handler/pull/10에서 typo 수정 완료했습니다

**Comment by forcecore** [comment]
Closed via #10
